<?php
/**
 * SwiftOtter_Base is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * SwiftOtter_Base is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with SwiftOtter_Base. If not, see <http://www.gnu.org/licenses/>.
 *
 * Copyright: 2015 (c) SwiftOtter Studios
 *
 * @author    Jesse Maxwell
 * @copyright Swift Otter Studios, 12/11/15
 * @package   default
 **/

/**
 * @var SwiftOtter_Blog_Block_Frontend_Sidebar_Category $this
 * @var SwiftOtter_Blog_Model_Category $_category
 */
?>
<?php // Base the group off of the first child: ?>
<?php $_categories = $this->getCategoryTree(); ?>

<?php foreach($_categories as $_category): ?>
    <option class="level-<?php echo $_category->getLevel(); ?>" value="<?php echo $_category->getUrl(); ?>"><?php echo $_category->getSpaces(); ?><?php echo $this->escapeHtml($_category->getTitle()); ?> <?php echo $this->__('(%s)', $this->escapeHtml($_category->getPostCount())); ?></option>
    <?php if (count($_category->getChildren())): ?>
        <?php echo $this->setCategories($_category->getChildren())->toHtml(); ?>
    <?php endif; ?>
<?php endforeach; ?>