<?php
/**
 * SwiftOtter_Base is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * SwiftOtter_Base is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with SwiftOtter_Base. If not, see <http://www.gnu.org/licenses/>.
 *
 * Copyright: 2016 (c) SwiftOtter Studios
 *
 * @author    Jesse Maxwell
 * @copyright Swift Otter Studios, 2/15/16
 * @package   default
 **/
?>
<a href="<?php echo Mage::helper('SwiftOtter_Blog')->getCurrentUrl(); ?>" class="blog-header">
    <h1 class="blog-header-primary"><?php echo $this->getHeading(); ?></h1>
    <h2 class="blog-header-secondary"><?php echo $this->getSecondaryHeading(); ?></h2>
</a>
