<?php
/**
 * @var $this SwiftOtter_Blog_Block_Frontend_List
 * @var $tag SwiftOtter_Blog_Model_Tag
 * @var $post SwiftOtter_Blog_Model_Post
 */
?>

<?php $list = $this->getList(); ?>

<div class="post-list">
    <?php if($this->getIsHomepage()): ?>
        <?php foreach($list as $post): ?>
            <?php echo $this->getChild('post.excerpt')->setPost($post)->toHtml(false); ?>
        <?php endforeach; ?>
    <?php else: ?>
        <?php foreach($list as $post): ?>
            <?php echo $this->getChild('single.post')->setPost($post)->toHtml(false); ?>
        <?php endforeach; ?>
    <?php endif; ?>
</div>

<?php echo $this->getChildHtml('blog_paging'); ?>
