<?php
/**
 * SwiftOtter_Base is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * SwiftOtter_Base is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with SwiftOtter_Base. If not, see <http://www.gnu.org/licenses/>.
 *
 * Copyright: 2015 (c) SwiftOtter Studios
 *
 * @author    Jesse Maxwell
 * @copyright Swift Otter Studios, 12/16/15
 * @package   default
 **/
?>
<?php if ($this->getNumberOfResults() > 0): ?>
    <h2 class="search-header"><?php echo $this->__('Search Results for "%s":', $this->getSearchTerm()); ?></h2>
    <?php $list = $this->getList(); ?>

    <div class="post-list">
        <?php foreach($list as $post): ?>
            <?php echo $this->getChild('single.post')->setPost($post)->toHtml(false); ?>
        <?php endforeach; ?>
    </div>

    <?php echo $this->getChildHtml('blog_paging'); ?>
<?php else: ?>
    <h2 class="no-results"><?php echo $this->__('No Results found for "%s"', $this->getSearchTerm()); ?></h2>
    <?php echo $this->getChildHtml('blog_no_search_results'); ?>
    <?php echo $this->getChildHtml('blog_search_form'); ?>
<?php endif; ?>
