<?php
/**
 * @var $this SwiftOtter_Blog_Block_Frontend_Single
 * @var $tag SwiftOtter_Blog_Model_Tag
 * @var $post SwiftOtter_Blog_Model_Post
 */
?>
<?php $post = $this->getPost() ?>
<?php $comments = $post->getComments(); ?>
<?php $commentNumber = $post->getNumberOfComments(); ?>
<?php $_titleBlock = $this->getChild('title.block'); ?>
<?php $_titleBlock->setPost($post); ?>

<div class="post-single<?php if(!$this->getIsSingle()): ?> post-in-list<?php endif; ?>">
    <?php if ($post): ?>
        <div class="post-header">
            <?php $_titleBlock->setFeatured(true); ?>
            <?php echo $_titleBlock->toHtml(); ?>
            <?php $thumbnails = $post->getThumbnailImages();?>
            <?php if (isset($thumbnails['post-thumbnail'])): ?>
                <?php $featured = $thumbnails['post-thumbnail']; ?>
                <div class="post-header-featured">
                    <div class="post-featured-container">
                        <img src="<?php echo $featured['url'] ?>" alt="<?php echo $post->getTitle(); ?> featured image" class="post-featured-image"/>
                    </div>
                </div>
            <?php endif; ?>
        </div>

        <div class="post-content">
            <?php echo $post->getContent(); ?>
        </div>

        <?php if ($this->getIsSingle()): ?>
            <h4>Share this post:</h4>
            <?php if ($this->helper('SwiftOtter_Blog')->getFacebook()): ?>
            <div class="post-share-item">
                <div class="fb-share-button" data-href="<?php echo $post->getUrl(); ?>" data-layout="button_count"></div>
            </div>
            <?php endif; ?>

            <?php if ($this->helper('SwiftOtter_Blog')->getTwitter()): ?>
            <div class="post-share-item">
                <a href="https://twitter.com/share" class="twitter-share-button">Tweet</a>
            </div>
            <?php endif; ?>

            <?php if ($this->helper('SwiftOtter_Blog')->getPinterest()): ?>
            <div class="post-share-item">
                <a href="//www.pinterest.com/pin/create/button/" data-pin-do="buttonBookmark"  data-pin-color="red">
                    <img src="//assets.pinterest.com/images/pidgets/pinit_fg_en_rect_red_20.png" />
                </a>
            </div>
            <?php endif; ?>

            <div class="post-share-item">
                <a href="mailto:?subject=Check out this post on Pleasant Hill Grain's Blog&body=Hello, <br> I thought this post was great. You can view it here: <?php echo $post->getUrl(); ?>" class="email-share-button">Email</a>
            </div>
        <?php endif; ?>

        <div class="post-meta-group post-meta-footer">
            <span class="post-meta post-time"><span class="post-meta-label"><?php echo $this->__('Posted'); ?>:</span> <?php echo date("F j\\, Y", strtotime($post->getDate())); ?></span>
            <?php if ($post->getNumberOfCategories() > 0): ?>
                <span class="post-meta post-category"><span class="post-meta-label"><?php echo $this->__('Category'); ?>:</span>
                    <?php $catIndex = 1; ?>
                    <?php foreach($post->getCategories() as $_category): ?>
                        <a href="<?php echo $_category->getUrl(); ?>"><?php echo $_category->getTitle(); ?></a><?php if ($catIndex < $post->getNumberOfCategories()): ?>, <?php endif; ?>
                        <?php $catIndex++; ?>
                    <?php endforeach; ?>
                </span>
            <?php endif; ?>
            <?php if ($post->getNumberofTags()): ?>
                <span class="post-meta post-tags"><span class="post-meta-label"><?php echo $this->__('Tags'); ?>:</span>
                    <?php $index = 1; ?>
                    <?php foreach($post->getTags() as $_tag): ?>
                        <a href="<?php echo $_tag->getUrl(); ?>"><?php echo $_tag->getTitle(); ?></a><?php if ($index < $post->getNumberofTags()): ?>, <?php endif; ?>
                        <?php $index++; ?>
                    <?php endforeach; ?>
                </span>
            <?php endif; ?>
        </div>

        <a href="<?php echo $post->getCommentUrl(); ?>" class="post-comment-link">
            <?php if ($comments): ?><?php echo $this->__('Read'); ?> <?php echo $commentNumber; ?> <?php echo $this->__('Comment'); ?><?php if ($commentNumber > 1): ?>s<?php endif; ?><?php else: ?><span class="post-comment-plus">&#43;</span><?php echo $this->__('Add a comment'); ?><?php endif; ?>
        </a>

        <?php if($this->getIsSingle()): ?>
            <a href="<?php echo Mage::helper('SwiftOtter_Blog')->getCurrentUrl(); ?>" class="meta-link"><?php echo $this->__('Return to blog'); ?></a>
            <?php $commentsBlock = $this->getChild('comments');?>
            <?php if ($commentsBlock): ?>
                <?php $commentsBlock->setComments($comments);?>
                <?php echo $commentsBlock->toHtml();?>
            <?php endif; ?>
        <?php endif; ?>

        <?php $productTagBlock = $this->getChild('product_tags'); ?>
        <?php if ($productTagBlock && $post->hasProductTags()): ?>
            <?php echo $productTagBlock->setProductTags($post->getProductTags())->toHtml(false); ?>
        <?php endif; ?>
    <?php else: ?>
        <h2><?php echo $this->__("I'm sorry, but we couldn't find the post."); ?></h2>
    <?php endif; ?>
</div>