<?php
/**
 * SwiftOtter_Base is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * SwiftOtter_Base is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with SwiftOtter_Base. If not, see <http://www.gnu.org/licenses/>.
 *
 * Copyright: 2015 (c) SwiftOtter Studios
 *
 * @author Jesse Maxwell
 * @copyright Swift Otter Studios, 5/22/15
 * @package default
 **/
/** @var SwiftOtter_Blog_Block_Frontend_Sidebar_Tag $this */
?>

<div class="sidebar-block">
    <h4 class="sidebar-title"><?php echo $this->__('Popular Tags'); ?>:</h4>
    <ul class="sidebar-tag-group">
        <?php foreach($this->getTags() as $tag): ?>
        <li class="sidebar-tag-item">
            <a href="<?php echo $tag->getUrl(); ?>" title="<?php echo $tag->getDescription(); ?>" class="sidebar-tag-link"><?php echo $tag->getTitle(); ?> <span class="sidebar-tag-count">(<?php echo $tag->getPostCount(); ?>)</span></a>
        </li>
    <?php endforeach; ?>
    </ul>
</div>