<?php
/**
 * SwiftOtter_Base is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * SwiftOtter_Base is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with SwiftOtter_Base. If not, see <http://www.gnu.org/licenses/>.
 *
 * Copyright: 2015 (c) SwiftOtter Studios
 *
 * @author    Jesse Maxwell
 * @copyright Swift Otter Studios, 12/16/15
 * @package   default
 **/
/** @var $this SwiftOtter_Blog_Block_Frontend_Sidebar_Widgets */
$_widgets = $this->getWidgets();
?>

<?php if ($_widgets): ?>
    <?php foreach($_widgets as $_widget): ?>
        <?php if ($this->getIsSearch($_widget)): ?>
            <?php echo $this->getChildHtml('search'); ?>
            <?php unset($_widget["widget"]); ?>
        <?php endif; ?>
        <?php if (isset($_widget["widget"])): ?>
            <div class="sidebar-block">
                <?php echo $_widget["widget"]; ?>
            </div>
        <?php endif; ?>
    <?php endforeach; ?>
<?php endif; ?>
