<?php
/**
 * SwiftOtter_Base is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * SwiftOtter_Base is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with SwiftOtter_Base. If not, see <http://www.gnu.org/licenses/>.
 *
 * Copyright: 2013 (c) SwiftOtter Studios
 *
 * @author Joseph Maxwell
 * @copyright Swift Otter Studios, 5/19/15
 * @package default
 **/
?>

<script type="text/javascript">
    jQuery('.comment-section').blog({
        submittingText: '<?php echo $this->__('Submitting...');?>',
        error: "<?php echo $this->__('Oh snap! It died and we aren\'t sure why.') ?>",
        errorDuplicate: "<?php echo $this->__('It looks like you already posted that comment!') ?>",
        error400: "<?php echo $this->__('Something didn\'t work quite right. We recommend that you try again.') ?>",
        error500: "<?php echo $this->__('We\'re really sorry, but it appears the server encountered a bug or other problem.') ?>"
    });
</script>